provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  meteo:
    lang: python3-http
    handler: ./meteo
    image: your-dockerhub-user/meteo:latest
    environment:
      write_debug: "true"
    secrets:
      - openweather-api-key
      - discord-webhook-url

  mete-pdf:
    lang: python3-http
    handler: ./mete-pdf
    image: your-dockerhub-user/mete-pdf:latest
    environment:
      write_debug: "true"
    secrets:
      - openweather-api-key

  weather-stats:
    lang: python3-http
    handler: ./weather-stats
    image: your-dockerhub-user/weather-stats:latest
    environment:
      write_debug: "true"
    secrets:
      - openweather-api-key
      - discord-webhook-url
