provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  meteo:
    lang: python3-http
    handler: ./meteo
    image: pradityoadi/meteo:latest
    environment:
      write_debug: "true"
      DB_HOST: "34.155.35.205"
      DB_PORT: "5432"
      DB_NAME: "openfaas_logs"
      DB_USER: "openfaas_user"
      DB_PASSWORD: "OpenFaas_User1"
    secrets:
      - openweather-api-key
      - discord-webhook-url
